name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/yourusername/my-react-app:latest
          push: false

      - name: Scan Docker image for vulnerabilities
        id: docker_scan
        uses: docker/scan-action@v1
        with:
          image: ghcr.io/yourusername/my-react-app:latest
          severity: critical,high

      - name: Check vulnerability scan results
        run: |
          if [ $(jq '.vulnerabilities | length' sarif.output.json) -ne 0 
]; then
            echo "High or Critical vulnerabilities found!"
            exit 1
          fi

      - name: Push Docker image to GHCR
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/yourusername/my-react-app:latest
          push: true

